CodeGuildCapstone/urls.py
from django.contrib import admin
from django.urls import include,path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('virtualbarkeep.urls')),
]

virtualbarkeep/urls.py
from django.urls import path
from . import views

app_name = 'vbk'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.searchalc, name='searchalc'),
    path('searchfood/', views.searchfood, name='searchfood'),
    path('register/', views.register, name='register' ),
    path('login_user/', views.login_user, name='login_user'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('savete/', views.ste, name='ste'),
    path('modalSte/<int:drink_id>/', views.modalSte, name='modalSte'),
    path('savetf/', views.stf, name='stf'),
    path('create/', views.add_event, name='add_event'),
    path('events/<int:event_id>/', views.event_view, name='event_view'),
    path('event_data/<int:event_id>/', views.event_data, name='event_data'),
    path('listdrinks/', views.search_list_drinks, name='listdrinks'),
    path('delete/<int:drink_id>/', views.delete_drink, name="delete"),


]

virtualbarkeep/models.py
from django.db import models
from django.contrib.auth.models import User



class Event(models.Model):
    name = models.CharField(max_length=200)
    attendees = models.IntegerField(default=2)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' ' + self.name


class SavedDrink(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    event = models.ForeignKey(Event, on_delete=models.PROTECT, related_name='drinks', null=True, blank=True)
    add_fav = models.BooleanField(default=False)
    name = models.CharField(max_length=100)
    instruction = models.CharField(max_length=400)
    image = models.CharField(max_length=300)

    def __str__(self):
        return self.user.username + ' ' + self.name

class SavedDrinkIngredient(models.Model):
    drink = models.ForeignKey(SavedDrink, on_delete=models.CASCADE, related_name='ingredients')
    name = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)

    def __str__(self):
        return self.drink.name + ' ' + self.name

class SavedFood(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    event = models.ForeignKey(Event, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    api_id = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.username + ' ' + self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class DrinkList(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=200)
    drink_id = models.CharField(max_length=20)

    def __str__(self):
        return self.name + ':' + self.drink_id

virtualbarkeep/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import SavedDrink, SavedFood, Event, SavedDrinkIngredient, DrinkList
from django.contrib.auth.decorators import login_required
import json


# Create your views here.
def index(request):
    return render(request, 'virtualbarkeep/index.html')


def searchalc(request):
    if request.user.is_authenticated:
        events = Event.objects.all().filter(user=request.user)
        context = {
            'events':events,
        }
        return render(request, 'virtualbarkeep/search.html', context)
    else:
        return render(request, 'virtualbarkeep/search.html')




def searchfood(request):
    return render(request, 'virtualbarkeep/food.html')


def register(request):
    if request.method == 'GET':
        return render(request, 'virtualbarkeep/login.html')
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    first_name = request.POST['firstname']
    last_name = request.POST['lastname']
    user = User.objects.create_user(username, email, password)
    user.first_name = first_name
    user.last_name = last_name
    user.save()
    return HttpResponseRedirect(reverse('vbk:index'))


def add_event(request):
    event_name = request.POST['eventname']
    attendees = request.POST['attendees']
    user = request.user
    saveevent = Event(name=event_name, attendees=attendees, user=user)
    saveevent.save()
    return HttpResponseRedirect(reverse('vbk:profile'))


def login_page(request):
    return render(request, 'virtualbarkeep/login.html')


def login_user(request):
    if request.method == 'GET':
        return render(request, 'virtualbarkeep/login.html')
    username = request.POST['username']
    password = request.POST['password']
    next = request.GET.get('next', '')
    print(request.POST)
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next != '':
            return HttpResponseRedirect(next)
        return HttpResponseRedirect(reverse('vbk:index'))
    if next == '':
        return HttpResponseRedirect(reverse('vbk:login') + '?message=failure')
    return HttpResponseRedirect(reverse('vbk:profile') + '?message=failure&next=' + next)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('vbk:index'))


# login required for the following views---

# save selected drink to event. User is given choices for which event to save to.
@login_required
def ste(request):
    data = json.loads(request.body)
    drink = data['name']
    event_id = data['event']
    event = Event.objects.get(id=event_id)
    print(event)
    instruction = data['instructions']
    image = data['image']
    addfav = False
    saveddrink = SavedDrink(add_fav=addfav, name=drink, image=image, instruction=instruction, user=request.user,event=event)
    saveddrink.save()
    for ingredient in data['ingredients']:
        savedingredient = SavedDrinkIngredient(drink=saveddrink, name=ingredient['name'], amount=ingredient['amount'])
        savedingredient.save()
    print(data)
    return HttpResponseRedirect(reverse('vbk:profile'))

def modalSte(request,drink_id):
    drink = SavedDrink.objects.get(id=drink_id)
    event_id = request.POST['event_id']
    drink.event_id = event_id
    drink.save()
    print(drink)
    return HttpResponseRedirect(reverse('vbk:profile'))

@login_required
def stf(request):
    data = json.loads(request.body)
    print(data)
    drink = data['name']
    instruction = data['instructions']
    image = data['image']
    if SavedDrink.objects.filter(user=request.user, name=drink, add_fav=True).exists():
        return HttpResponse("Already exists")

    addfav = True
    saveddrink = SavedDrink(add_fav=addfav, name=drink, image=image, instruction=instruction, user=request.user)
    saveddrink.save()
    for ingredient in data['ingredients']:
        savedingredient = SavedDrinkIngredient(drink=saveddrink, name=ingredient['name'], amount=ingredient['amount'])
        savedingredient.save()
    print(data)
    return HttpResponseRedirect(reverse('vbk:profile'))


@login_required
def profile(request):
    events = Event.objects.all().filter(user=request.user)
    drinks = SavedDrink.objects.all().filter(user=request.user, add_fav=True)
    ingredients = SavedDrinkIngredient.objects.all()
    has_favorites = request.user.saveddrink_set.filter(add_fav=True).count()>0
    context = {
        'events': events,
        'drinks': drinks,
        'ingredients': ingredients,
        'has_favorites': has_favorites,
    }
    return render(request, 'virtualbarkeep/profile.html', context)

@login_required
def event_view(request,event_id):
    event = Event.objects.get(id=event_id)
    context = {
        'event': event,

    }
    return render(request, 'virtualbarkeep/events.html', context)

def event_data(request, event_id):
    event = Event.objects.get(id=event_id)
    data = {
        'name': event.name,
        'attendees': event.attendees,
        'drinks': [],
    }
    for drink in event.drinks.all():
        ingredients = []
        for ingredient in drink.ingredients.all():
            ingredients.append({
                'name':ingredient.name,
                'amount':ingredient.amount,
            })
            print(ingredient.name)

        data['drinks'].append({
            'name': drink.name,
            'instructions': drink.instruction,
            'image': drink.image,
            'ingredients': ingredients,
            })
    return JsonResponse(data)

def search_list_drinks(request):
    list = DrinkList.objects.all()
    data = {
        'drinks':[]
        }
    for drink in list:
        data['drinks'].append({
            'name':drink.name,
            'drink_id':drink.drink_id
        })
    return JsonResponse(data)

def random_drink_view(request):
    pass

def delete_drink(request, drink_id):
    favorite_drink = SavedDrink.objects.get(id=drink_id)
    favorite_drink.delete()
    return render(request, 'virtualbarkeep/index.html')

virtualbarkeep/templates/virtualbarkeep/events.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include './navbar.html %}


<div id="app">
<div class="header-container">
<div class="space-mobile"></div>
<div class="event-container">
<div class="event-view">
  <div class="event-data-side">
    <div class="event-data-header">
        <h5>[[event.name]]</h5>
    </div>
      <div class="event-btn-cont" v-for="drink in event.drinks">
          <ul>
              <li><a class="event-btn" @click="selectedDrink=drink">[[drink.name]]</a></li>
          </ul>
      </div>
      <div class="event-image" v-if="selectedDrink.ingredients.length > 0">
          <img v-bind:src='selectedDrink.image' alt="Avatar" style="width:200px;height:200px;border-radius:10px 50px;margin: 20px">
      </div>
  </div>
  <div class="event-data-main" v-if="selectedDrink.ingredients.length >0">
      <div class="event-drink-inst">
          <p>[[selectedDrink.instructions]]</p>
      </div>
      <div class="event-drink-ingredients">
          <ul>
              <li v-for="ingredient in selectedDrink.ingredients">[[ingredient.name]] : [[ingredient.amount]]</li>
          </ul>
      </div>
  </div>
</div>
</div>
</div>
</div>


<script type="text/javascript">
    let app = new Vue({
        el: '#app',
        delimiters: [
            '[[',
            ']]',
        ],
        data: {
            event: {
                name: '',
                attendees: '0',
                drinks: [],
            },
            selectedDrink:{
                ingredients:[],
                instruction:"",
            },
        },
        created: function () {
            axios({
                method: 'get',
                url: "{% url 'vbk:event_data' event.id %}"

            })
                .then(response => {
                    console.log(response.data)
                    this.event=response.data
                })
        },
        methods: {
            viewDrink: function (drink) {
            }
        }
    })

</script>

{% endblock %}

virtualbarkeep/templates/virtualbarkeep/food.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include './navbar.html' %}

<div class="space"></div>
<div id="foodapp">
<div class="header-container">
    <div class="search-box">
        <div class="jumbotron jumbotron-fluid jumbotron2">
            <h1 class="display-4">Food Search</h1>
            <p class="lead">What do you want to eat?</p>
            <input type="text" v-model='foodName' v-on:keyup.enter='startFind'>

            <a href="#btn-bar" class="search-btn" v-on:click="startFind">Search</a>
        </div>
    </div>
</div>









</div>
<script>
// Vue App ---
    let app = new Vue({
        el: '#foodapp',
        delimiters: [
            '[[',
            ']]',
        ],
        data: {
            foodName: '',
            category:'',
            foodResults: [],
            foodResults2: [],
            selectedEvent: '',

        },
        methods: {
            mergeIngredients: function (drink) {
                let ingredients = []
                for (let i = 1; i <= 15; ++i) {
                    let name = drink['strIngredient' + i]
                    let amount = drink['strMeasure' + i]
                    if (name == null) {
                        break
                    }
                    if (amount == null) {
                        amount = ''
                    }
                    ingredients.push({
                        name: name,
                        amount: amount
                    })
                }
                return ingredients
            },
            startFind: function () {
                axios({
                    method: 'get',
                    url: 'https://www.thecocktaildb.com/api/json/v1/1/search.php',
                    params: {
                        s: this.drinkName,
                    }
                })
                    .then((response) => {
                        // if (response.data.drink == null){
                        //     alert('Try again')
                        //     return
                        // }
                        let drink_data = response.data.drinks
                        this.drinkResults = []
                        for (let i = 0; i < drink_data.length; ++i) {
                            this.drinkResults.push({
                                name: drink_data[i].strDrink,
                                instructions: drink_data[i].strInstructions,
                                ingredients: this.mergeIngredients(drink_data[i]),
                                image: drink_data[i].strDrinkThumb,
                            })
                        }

                    })
            },
            advancedFind: function (nameChoice) {
                axios({
                    method: 'get',
                    url: 'https://www.thecocktaildb.com/api/json/v1/1/search.php',
                    params: {
                        s: nameChoice,
                    }
                }).then((response) => {
                    console.log(response.data.drinks)
                    let drink_data2 = response.data.drinks
                    this.drinkResults2 = []
                    for (let i = 0; i < drink_data2.length; ++i) {
                        this.drinkResults2.push({
                            name: drink_data2[i].strDrink,
                            instructions: drink_data2[i].strInstructions,
                            ingredients: this.mergeIngredients(drink_data2[i]),
                            image: drink_data2[i].strDrinkThumb,
                        })
                    }

                })

            },
            addDrinkToFavorites: function (drink) {
                console.log(drink)
                axios({
                    method: 'post',
                    url: "{% url 'vbk:stf' %}",
                    data: drink,
                    headers: {
                        'X-CSRFToken': '{{csrf_token}}',
                    }

                }).then(response => {
                    console.log(response)
                })
            },
            addDrinkToEvent: function () {
                let drink = this.selectedDrink
                drink.event = this.selectedEvent
                console.log(drink)
                axios({
                    method: 'post',
                    url: "{% url 'vbk:ste' %}",
                    data: drink,
                    headers: {
                        'X-CSRFToken': '{{csrf_token}}',
                    }

                }).then(response => {
                    console.log(response)
                })
            }
        }
    });

    // end vue
    function showCard() {
        document.getElementById('cardHide').setAttribute("class", "card1");
    }


</script>





{% endblock %}

virtualbarkeep/templates/virtualbarkeep/index.html
<!--The index page is the home view and contains the search box with what your searching-->
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include './navbar.html' %}

<div id="random">
    <div class="header-container">
        <div class="index-header">
            <div class="jumbotron jumbotron2">
                <img src="{% static 'virtualbarkeep/images/logotry1.jpg' %}" height="200px" width="200px" alt="">
                <h1 class="display-4" style="color: white"> Hello,</h1>
                <h3 class="lead" style="color:white"><strong>welcome to your very own virtual drink assistant..</strong>
                </h3>
                <hr class="my-4">
                <p>take your taste buds on a journey</p>
                <a class="btn btn-index btn-lg" href="{% url 'vbk:searchalc' %}" role="button">SEARCH FOR DRINKS</a>
                <a class="btn btn-index btn-lg" @click="randomFind" href="#smoothscroll" role="button">SHOW ME
                    RANDOM</a>
            </div>
        </div>
    </div>
    <div class="space" id="smoothscroll"></div>
    <div class="space"></div>
    <div class="cluster-cont " v-if="randomDrinks.length > 0">
        <div v-for="drink in randomDrinks" @click="selectedDrink=drink" class="card">
            <a class="card_image" data-target="#drinkModal" data-toggle="modal">
                <img v-bind:src="[[drink.image]]" alt="">
            </a>
            <div class="card_title title-white">
                <p>[[drink.name]]</p>
            </div>
        </div>
    </div>

    <!--    modal-->
    <div v-if="selectedDrink != null" class="modal fade" id="drinkModal" tabindex="-1" role="dialog"
         aria-labelledby="drinkModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="drinkModalTitle">[[selectedDrink.name]]</h5>
                </div>

                <div class="modal-body">
                    <h5>[[selectedDrink.instructions]]</h5>
                    <table v-for="ingredient in selectedDrink.ingredients">
                        <tr>
                            <td>[[ingredient.name]]: <strong>[[ingredient.amount]]</strong></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div><!--app ending div-->
<script src="https://unpkg.com/vue"></script>
<script>
    let app = new Vue({
        el: '#random',
        delimiters: [
            '[[',
            ']]',
        ],
        data: {
            randomDrinks: [],
            selectedDrink: null,
            showModal: false,

        },
        methods: {
            mergeIngredients: function (drink) {
                let ingredients = []
                for (let i = 1; i <= 15; ++i) {
                    let name = drink['strIngredient' + i]
                    let amount = drink['strMeasure' + i]
                    if (name == null) {
                        break
                    }
                    if (amount == null) {
                        amount = ''
                    }
                    ingredients.push({
                        name: name,
                        amount: amount
                    })
                }
                return ingredients
            },
            randomFind: function () {
                axios({
                    method: 'get',
                    url: 'https://www.thecocktaildb.com/api/json/v2/9973533/randomselection.php',
                    params: {},

                })
                    .then((response) => {
                        let drinks_data = response.data.drinks
                        console.log(drinks_data)
                        this.randomDrinks = []
                        for (let i = 0; i < drinks_data.length; ++i) {
                            this.randomDrinks.push({
                                name: drinks_data[i].strDrink,
                                image: drinks_data[i].strDrinkThumb,
                                instructions: drinks_data[i].strInstructions,
                                ingredients: this.mergeIngredients(drinks_data[i]),
                            })
                        }
                        console.log(this.randomDrinks)
                    })
            },
        },
    })
</script>

{% endblock %}

virtualbarkeep/templates/virtualbarkeep/landing.html
{% load static %}
<div class="header-container">
    <div>
        <nav>
            {% include './navbar.html' %}
        </nav>
    </div>
    <div class="search-header">
        <div class="logoimg">
            <img src="{% static 'virtualbarkeep/images/logo.png' %}" height="300px" width="300px" alt="">
        </div>
        <div class="jumbotron">
            <h1 class="display-4">Hello,</h1>
            <p class="lead">Welcome to your very own, and personal Virtual Barkeep.. </p>
             <hr class="my-4">
            <p>Get rid of the "what do I want?" in your life and let your Barkeep give you some ideas.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'virtualbarkeep:searchalc' %}" role="button">Search Alcohol</a>
            <a class="btn btn-primary btn-lg" href="#searchid" role="button">Search Food</a>
            <a class="btn btn-primary btn-lg" href="#searchid" role="button">Roll the dice!</a>
        </div>
    </div>

</div>

virtualbarkeep/templates/virtualbarkeep/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include './navbar.html' %}
<div class="header-container">
<div class="login-contain">
    <div class="space-mobile"></div>
    <div class="log-form jumbotron">
        <h2>Login to Create and Save Events</h2>
        <form action="{% url 'vbk:login_user' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label>Username</label>
                <input name="username" type="text" class="form-control" placeholder="Username" aria-label="Username"
                       aria-describedby="basic-addon1">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input name="password" type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
    </div>

{% endblock %}

virtualbarkeep/templates/virtualbarkeep/navbar.html
<nav class="navbar sticky navbar-light" id="navbar">
    {% if not user.is_anonymous %}
    <div>Welcome {{request.user.first_name}}
    <li><a href="{% url 'vbk:profile' %}">View Profile</a></li>
    </div>
    {% endif %}
    {% if user.is_anonymous %}
    <div class="logo-div"><a class="navbar-brand" href="{% url 'vbk:index' %}">V | B</a></div>
    {% endif %}
        <div>
            <ul>
                <li><a href="{% url 'vbk:index' %}">Home</a></li>
                {% if user.is_anonymous %}
                <li><a href="{% url 'vbk:login' %}">Login</a></li>
                <li><a type="button" data-toggle="modal" data-target="#registerModal">
                Register</a>
                </li>
                {% endif %}
                <li>|</li>
                <li><a href="{% url 'vbk:logout' %}">Logout</a></li>
            </ul>
        </div>
</nav>
<!-- Modal -->
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register To Create Events!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'vbk:register' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="First Name" aria-label="First Name" aria-describedby="basic-addon1" name="firstname">
                            <input type="text" class="form-control" placeholder="Last Name" aria-label="Last Name" aria-describedby="basic-addon1" name="lastname">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name="username">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" name="email"
                                   aria-describedby="emailHelp">
                            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                                else.</small>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

virtualbarkeep/templates/virtualbarkeep/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include './navbar.html %}


<div class="header-container">
    <div class="jumbotron jumbotron-fluid jumbotron3">
        <h1>Welcome {{request.user.first_name}}</h1>
        <p>Explore your favorite drinks | Plan your events</p>
        <div class="dropdown">
            <a class="btn btn-index btn-lg dropdown-toggle" role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Events</a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                {% for event in events %}
                <a id="eventbtn" class="dropdown-item" href="{% url 'vbk:event_view' event.id %}">{{event.name}}</a>
                {% endfor %}
            </div>
            {% if has_favorites %}
            <div>
                <a class="btn btn-index btn-lg" href="#favoritecard" role="button">Favorites</a>
            </div>
            {% endif %}
        </div>
        <div>
            <a class="btn btn-index btn-lg" role="button" type="button" data-toggle="modal" data-target="#eventModal">Create Event</a>
        </div>
            <a class="btn btn-index btn-lg" href="{% url 'vbk:searchalc' %}" role="button">Search for drinks</a>
    </div>
</div>
{% if has_favorites %}
<div class="main-cont" id="favoritecard">
    <div class="random-cont" id="randomcont">
        {% for drink in drinks %}
        <div class="card">
            <a class="card_image" data-target="#drinkModal{{forloop.counter}}" data-toggle="modal">
                <img src="{{drink.image}}" alt="">
            </a>
            <div class="card_title title-white">
                <p>{{drink.name}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <!--    </div>-->
    {% for drink in drinks %}
    <!--drink modal-->
    <div class="modal fade" id="drinkModal{{forloop.counter}}" tabindex="-1" role="dialog"
         aria-labelledby="drinkModalTitle{{forloop.counter}}" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="drinkModalTitle{{forloop.counter}}">{{drink.name}}</h5>
                </div>

                <div class="modal-body">
                    <h5>{{drink.instruction}}</h5>
                    {% for ingredient in drink.ingredients.all %}
                    <table>
                        <tr>
                            <td>{{ingredient.name}}: <strong>{{ingredient.amount}}</strong></td>
                        </tr>
                    </table>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a type="button" class="btn btn-primary" href="{% url 'vbk:delete' drink.id %}">Delete From Favorites</a>
                    <form action="{% url 'vbk:modalSte' drink.id %}" method="post">
                        {% csrf_token %}
                        <select name="event_id">
                            <option>Choose Event</option>
                            {% for event in events %}

                            <option value="{{event.id}}">{{event.name}}</option>
                            {% endfor %}
                        </select>
                        <button type="submit" class="btn btn-primary">Add to Event</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    <!--modals-->
    <div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register To Create Events!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'vbk:add_event' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" placeholder="Event Name" aria-label="Event"
                                   aria-describedby="basic-addon1" name="eventname">
                            <label for="number">Number of Attendees</label>
                            <input type="number" class="form-control" name="attendees"
                                   aria-describedby="emailHelp">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!--end modal-->


    {% endblock %}

virtualbarkeep/templates/virtualbarkeep/reglog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% include './navbar.html' %}

{% endblock %}